### ISSUE TITLE
스켈레톤 작성

### ISSUE THREAD

**Issue by coneseo** [coneseo/calculator#1]
프로젝트를 시작하기 위한 스켈레톤 작성

-main() 함수 작성

**Comment by irerin07** [comment]
사칙연산을 담당하는 각각의 클래스를 작성하는게 좋을 것 같습니다.

**Comment by coneseo** [comment]
> 사칙연산을 담당하는 각각의 클래스를 작성하는게 좋을 것 같습니다.

더하기 곱하기 나누기 빼기를 추가해요
